### ISSUE TITLE
Dynamic tank upgrade issue.

### ISSUE THREAD

**Issue by Yoofle** [WingsOfLife/DynamicLiquidTanks_v2.0#12]
So there is an issue with dynamic tanks. As a single tank they work fine but when i tried to upgrade it, it broke.
I tried the upgrade module on 3 sides and the bottom, next to the controller. Crashed with both types of upgrade, crashed with no pipe connected and with pipe connected and crashed in creative and survival. 
Here is the crash report: pastebin.com/qcfvcwCh
If you need any further information, contact me in an irc chatroom channel: #GG Username ExoKruzer or Gilgs. Thanks

**Comment by WingsOfLife** [comment]
Are you playing on client or server?

**Comment by Yoofle** [comment]
I run FTB Monster, Horizons, and Tech World 2. Guess i should have mentioned this. It is coming from our Monster server.

**Comment by WingsOfLife** [comment]
I'll check into this and find the error. Thank you :)
