### ISSUE TITLE
Controller related crash

### ISSUE THREAD

**Issue by NicolaosGreene** [WingsOfLife/DynamicLiquidTanks_v2.0#14]
I was messing around with the DLT tanks and was trying various things with them to test them. I found this client side crash when I broke the entire previous tank and then replaced the controller. Furthermore, the tank's infor said it had -49,000 mB in it.
First crash: http://pastebin.com/jN0JCqWj
Subsequent Crashes: http://pastebin.com/RXqxRiaD

**Comment by WingsOfLife** [comment]
What version of the mod are you using?

**Comment by NicolaosGreene** [comment]
0.0.5a

**Comment by WingsOfLife** [comment]
Did you place the block by hand? For some reason the tileentity was not placed with the block, not sure how this could happen.

**Comment by NicolaosGreene** [comment]
Yes I did place the block by hand however I was in creative mode if that makes a difference

**Comment by WingsOfLife** [comment]
Found the issue. It has been fixed in the next version.
