### ISSUE TITLE
NPE on placed tank controller

### ISSUE THREAD

**Issue by SigurdCole** [WingsOfLife/DynamicLiquidTanks_v2.0#15]
Hi! I'm using FTB Horizons, and I've started getting this error. I traced it back to the only two tank controllers in my base. It's not crashing, but it's throwing this error every time I'm around them or look in their direction, making for pretty substantial slowdowns. Here's the (truncated) log.

http://pastebin.com/qYijQcbg

**Comment by WingsOfLife** [comment]
This is an issue with JourneyMap trying to get the render colour of my tanks. Due to the camo features I cannot fix this, it will have to be fixed on their end.
