### ISSUE TITLE
upgrade bugs

### ISSUE THREAD

**Issue by Rainboww** [WingsOfLife/DynamicLiquidTanks_v2.0#19]
after we upgraded to DLT 0.0.7 from 0.0.5 (skipped 0.0.6 due to issues with ars magica) we noticed 2 things, both to do with upgrades: firstly, the capacity upgrade seems entirely absent right now, and secondly, the config option to enable or disable upgrades does the exact oposite - with upgrades set to false, you can craft them, otherwise you can't.

**Comment by Rainboww** [comment]
..or rather, the basic upgrade (unusable) takes its place. Didn't know that. Anyway, the config option bug still stands

**Comment by WingsOfLife** [comment]
Thank you for the note. I will fix that in the next version. And you are correct capacity upgrades were removed; however, any tanks that currently have them should retain them unless the Upgrade Manager is updated.
