### ISSUE TITLE
Crash upon taking and replacing cleansing water.

### ISSUE THREAD

**Issue by Unrepentant-Atheist** [WingsOfLife/DynamicLiquidTanks_v2.0#2]
Taking cleansing water, and replacing it in the world results in a crash.

https://privatepaste.com/efe62e7cd0

**Comment by WingsOfLife** [comment]
This does not show any errors in relation to DLT2. I looks like it is the result of a mod trying to modify the vanilla inventory. I also could not replicate this issue.
