### ISSUE TITLE
crash when draining liquid XP

### ISSUE THREAD

**Issue by jdratlif** [WingsOfLife/DynamicLiquidTanks_v2.0#22]
I setup a 3x3 area with a controller in the center and tanks all around. There's an open blocks auto enchanting table on top the controller which is set to auto drink from the bottom. When the level of liquid XP goes below a certain amount, the server crashes.

I can duplicate this reliably in a test world using only forge, nei, openblocks, and dynamic tanks (0.07).

http://www.technoplaza.net/temp/dt-crashlog.txt

**Comment by WingsOfLife** [comment]
Should be fixed in 0.0.8. If not this seems to be an open blocks issue.
