### ISSUE TITLE
Crash Related to Controller Placement

### ISSUE THREAD

**Issue by Mirandatz** [WingsOfLife/DynamicLiquidTanks_v2.0#23]
I found out htat if you break a controller it still retains the liquids... So I decided to sploit it to transfer liquids over distance, since I'm a cheap-ass.

I created a tank in my base with 13 blocks and no controller... Then I created a controller a put it bellow my Coke Oven to drain the Creosote Oil...  I destroyed the controller and tried to put it near the 13 tank blocks... But as soon as I place it in the floor I'm disconnected from the server with a error msg.

**Comment by Mirandatz** [comment]
The error message is Disconnected by Server. Internal server error.
The other players don't crash.
If I login the block is placed but the tank doesn't display any liquid... If I right click it says 0 buckets... 
If I break the controller and pick it up it says, in the inventory
Tank Controller (Pre-Filled) 3740:6352
Hold SHIFT for information.
Dynamic Liquid Tanks 2

If I press SHIFT it says
Tank Controller (Pre-Filled) 3740:6352
Creosote
-16,780 mB
Dynamic Liquid Tanks 2

**Comment by WingsOfLife** [comment]
Old version. Issue no longer relevant
