### ISSUE TITLE
Crash with EnderIO pressurized fluid conduit

### ISSUE THREAD

**Issue by ghost** [WingsOfLife/DynamicLiquidTanks_v2.0#24]
http://pastebin.com/z1zgXZfu
I have a pressurized fluid conduit taking MFR Mob Essence from a Dynamic Tanks 2 Controller and sending it into a EnderIO Dimensional Transceiver
It crashes on world load
Here is the post on the EnderIO Minecraftforum Thread: http://www.minecraftforum.net/topic/1937619-171615-ender-io-how-many-pipes-in-one-block-10-less-beta-than-ever/page__st__1200#entry30366667

**Comment by Keridos** [comment]
Having the same issue aswell, please fix that.

**Comment by WingsOfLife** [comment]
Old version. Fixed.
