### ISSUE TITLE
Client crash when using LXP absorber from Immibis' Liquid XP mod

### ISSUE THREAD

**Issue by BrianOxide** [WingsOfLife/DynamicLiquidTanks_v2.0#31]
Placed LXP absorber on top of tank controller with attached tank.  Stepped onto absorber and this happened :

---- Minecraft Crash Report ----
// Oh - I know what I did wrong!

Time: 08/11/14 18:51
Description: Unexpected error

java.lang.NullPointerException: Unexpected error
    at doc.mods.dynamictanks.client.render.RenderStruture.renderWorldBlock(RenderStruture.java:46)
    at cpw.mods.fml.client.registry.RenderingRegistry.renderWorldBlock(RenderingRegistry.java:118)
    at net.minecraft.src.FMLRenderAccessLibrary.renderWorldBlock(FMLRenderAccessLibrary.java:53)
    at net.minecraft.client.renderer.RenderBlocks.func_147805_b(RenderBlocks.java:296)
    at net.minecraft.client.renderer.WorldRenderer.func_147892_a(WorldRenderer.java:181)
    at net.minecraft.client.renderer.RenderGlobal.func_72716_a(RenderGlobal.java:1530)
    at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1187)
    at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1011)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:990)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:887)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Stacktrace:
    at doc.mods.dynamictanks.client.render.RenderStruture.renderWorldBlock(RenderStruture.java:46)
    at cpw.mods.fml.client.registry.RenderingRegistry.renderWorldBlock(RenderingRegistry.java:118)
    at net.minecraft.src.FMLRenderAccessLibrary.renderWorldBlock(FMLRenderAccessLibrary.java:53)
    at net.minecraft.client.renderer.RenderBlocks.func_147805_b(RenderBlocks.java:296)
    at net.minecraft.client.renderer.WorldRenderer.func_147892_a(WorldRenderer.java:181)
    at net.minecraft.client.renderer.RenderGlobal.func_72716_a(RenderGlobal.java:1530)
    at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1187)

-- Affected level --
Details:
    Level name: MpServer
    All players: 1 total; [EntityClientPlayerMP['R401JL'/39177, l='MpServer', x=256.98, y=67.80, z=396.25]]
    Chunk stats: MultiplayerChunkCache: 225, 225
    Level seed: 0
    Level generator: ID 00 - default, ver 1. Features enabled: false
    Level generator options: 
    Level spawn location: World: (188,64,256), Chunk: (at 12,4,0 in 11,16; contains blocks 176,0,256 to 191,255,271), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
    Level time: 347739 game time, 388449 day time
    Level dimension: 0
    Level storage version: 0x00000 - Unknown?
    Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
    Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
    Forced entities: 43 total; [EntityZombie['Zombie'/45312, l='MpServer', x=251.03, y=27.00, z=384.50], EntityClientPlayerMP['R401JL'/39177, l='MpServer', x=256.98, y=67.80, z=396.25], EntitySheep['Sheep'/39169, l='MpServer', x=232.91, y=66.00, z=372.94], EntityZombie['Zombie'/45313, l='MpServer', x=205.50, y=42.00, z=364.50], EntityCreeper['Creeper'/45314, l='MpServer', x=197.50, y=42.00, z=361.50], EntityCreeper['Creeper'/45315, l='MpServer', x=199.50, y=42.00, z=362.50], EntityCreeper['Creeper'/45316, l='MpServer', x=199.50, y=42.00, z=359.50], EntityConcussionCreeper['Concussion Creeper'/45317, l='MpServer', x=206.50, y=42.00, z=365.50], EntityConcussionCreeper['Concussion Creeper'/45318, l='MpServer', x=209.50, y=42.00, z=366.50], EntitySheep['Sheep'/39946, l='MpServer', x=202.56, y=68.00, z=403.34], EntitySheep['Sheep'/39947, l='MpServer', x=193.97, y=72.00, z=419.25], EntitySheep['Sheep'/39948, l='MpServer', x=207.78, y=66.00, z=426.50], EntitySheep['Sheep'/39964, l='MpServer', x=202.22, y=69.00, z=461.38], EntitySheep['Sheep'/39965, l='MpServer', x=206.50, y=69.00, z=462.31], EntitySheep['Sheep'/39966, l='MpServer', x=206.50, y=69.00, z=463.53], EntitySheep['Sheep'/39977, l='MpServer', x=186.50, y=70.00, z=414.50], EntitySheep['Sheep'/39979, l='MpServer', x=188.50, y=72.00, z=416.50], EntitySheep['Sheep'/39980, l='MpServer', x=186.13, y=71.00, z=420.53], EntitySheep['Sheep'/40764, l='MpServer', x=197.50, y=75.00, z=471.50], EntitySheep['Sheep'/40765, l='MpServer', x=195.50, y=76.00, z=469.50], EntitySheep['Sheep'/40766, l='MpServer', x=197.59, y=74.00, z=464.25], EntitySheep['Sheep'/40767, l='MpServer', x=203.63, y=68.00, z=460.53], EntitySheep['Sheep'/40768, l='MpServer', x=189.50, y=69.00, z=465.53], EntitySheep['Sheep'/40771, l='MpServer', x=279.63, y=66.00, z=467.19], EntitySheep['Sheep'/39236, l='MpServer', x=290.84, y=64.00, z=451.69], EntitySheep['Sheep'/40772, l='MpServer', x=270.59, y=65.00, z=467.81], EntityItem['item.item.egg'/44368, l='MpServer', x=196.03, y=67.13, z=345.88], EntitySheep['Sheep'/39269, l='MpServer', x=226.91, y=67.00, z=460.09], EntitySheep['Sheep'/39270, l='MpServer', x=226.81, y=65.00, z=458.25], EntityChicken['Chicken'/149, l='MpServer', x=195.47, y=67.00, z=343.53], EntityChicken['Chicken'/150, l='MpServer', x=194.34, y=67.00, z=344.38], EntityChicken['Chicken'/151, l='MpServer', x=194.34, y=67.00, z=345.78], EntityChicken['Chicken'/152, l='MpServer', x=202.34, y=67.00, z=347.47], EntityChicken['Chicken'/171, l='MpServer', x=210.59, y=67.00, z=335.53], EntityChicken['Chicken'/172, l='MpServer', x=224.41, y=66.00, z=333.63], EntityChicken['Chicken'/173, l='MpServer', x=220.50, y=67.00, z=337.50], EntityEnderman['Enderman'/45229, l='MpServer', x=203.41, y=19.00, z=368.22], EntityChicken['Chicken'/174, l='MpServer', x=209.56, y=67.00, z=331.56], EntityItem['item.item.egg'/43972, l='MpServer', x=210.59, y=67.13, z=331.09], EntityItem['item.item.ganyssurface.poop'/44495, l='MpServer', x=226.19, y=65.13, z=458.41], EntityItem['item.item.egg'/45008, l='MpServer', x=218.81, y=67.13, z=337.91], EntitySheep['Sheep'/39921, l='MpServer', x=217.50, y=66.00, z=425.50], EntitySheep['Sheep'/39928, l='MpServer', x=216.19, y=64.00, z=435.38]]
    Retry entities: 0 total; []
    Server brand: fml,forge
    Server type: Non-integrated multiplayer server
Stacktrace:
    at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:373)
    at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2433)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:916)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
    Minecraft Version: 1.7.10
    Operating System: Windows 7 (amd64) version 6.1
    Java Version: 1.8.0_25, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 313586616 bytes (299 MB) / 1072410624 bytes (1022 MB) up to 2110783488 bytes (2013 MB)
    JVM Flags: 7 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -Xms512M -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn350M
    AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
    FML: MCP v9.05 FML v7.10.85.1230 Minecraft Forge 10.13.2.1230 89 mods loaded, 89 mods active
    mcp{9.05} [Minecraft Coder Pack](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    FML{7.10.85.1230} [Forge Mod Loader](forge-1.7.10-10.13.2.1230.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    Forge{10.13.2.1230} [Minecraft Forge](forge-1.7.10-10.13.2.1230.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    appliedenergistics2-core{rv1-stable-1} [AppliedEnergistics2 Core](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    Aroma1997Core{1.0.2.11} [Aroma1997Core](Aroma1997Core-1.7.10-1.0.2.11.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    CodeChickenCore{1.0.4.29} [CodeChicken Core](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    <CoFH ASM>{000} [CoFH ASM Data Initialization](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    MobiusCore{1.2.3} [MobiusCore](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    NotEnoughItems{1.0.3.64} [Not Enough Items](NotEnoughItems-1.7.10-1.0.3.64-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    DC1{3.4.2.19} [KingCore]([1.7.2+] KingCore v3.4.2.19.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    AS1{3.2.1.26} [Arcane Scrolls]([1.7.10] ArcaneScrolls v3.2.1.26.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    advancedgenetics{1.5.7} [Advanced Genetics](advancedgenetics-1.7.10-1.5.7.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    AppleCore{1.0.1} [AppleCore](AppleCore-mc1.7.10-1.0.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    appliedenergistics2{rv1-stable-1} [Applied Energistics 2](appliedenergistics2-rv1-stable-1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    Aroma1997CoreHelper{1.0.2.11} [Aroma1997Core|Helper](Aroma1997Core-1.7.10-1.0.2.11.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    BetterChests{1.1.1.7} [BetterChests](BetterChests-1.7.10-1.1.1.7.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    BiblioCraft{1.8.2} [BiblioCraft](BiblioCraft[v1.8.2][MC1.7.10].jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    CarpentersBlocks{3.3.0.1} [Carpenter's Blocks](Carpenter's Blocks v3.3.0.1 - MC 1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    ChickenChunks{1.3.4.14} [ChickenChunks](ChickenChunks-1.7.10-1.3.4.14-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    chisel{1.5.7} [Chisel](Chisel-1.7.10-1.5.7.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    CoFHCore{1.7.10R3.0.0B6} [CoFH Core](CoFHCore-[1.7.10]3.0.0B6-32.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    ComputerCraft{1.65} [ComputerCraft](ComputerCraft1.65.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    dynamictanks{1.0} [Dynamic Liquid Tanks 2.1](dynamictanks-1.1.03.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    MineFactoryReloaded{1.7.10R2.8.0RC3} [MineFactory Reloaded](MineFactoryReloaded-[1.7.10]2.8.0RC3-591.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    Baubles{1.0.1.8} [Baubles](Baubles-1.7.10-1.0.1.8.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    Thaumcraft{4.2.1.4} [Thaumcraft](Thaumcraft-1.7.10-4.2.1.4.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    EnderIO{1.7.10-2.1.8.260} [Ender IO](EnderIO-1.7.10-2.1.8.260.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    EnderZoo{1.7.10-1.0.2.7_beta} [Ender Zoo](EnderZoo-1.7.10-1.0.2.7_beta.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    EE3{0.2.362} [Equivalent Exchange 3](EquivalentExchange3-1.7.10-0.2.362.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    ThermalFoundation{1.7.10R1.0.0B3} [Thermal Foundation](ThermalFoundation-[1.7.10]1.0.0B3-8.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    ForgeMultipart{1.1.0.311} [Forge Multipart](ForgeMultipart-1.7.10-1.1.0.311-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    ExtraUtilities{1.1.0k} [Extra Utilities](extrautilities-1.1.0k.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    fluxedtrinkets{0.52} [Fluxed Trinkets](Fluxed Trinkets-1.7.10-1.0.52.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    ganysend{1.8.3} [Gany's End](Ganys End-1.8.3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    ganysnether{1.7.5} [Gany's Nether](Ganys Nether-1.7.5.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    ganyssurface{1.9.3} [Gany's Surface](Ganys Surface-1.9.3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    ImmibisCore{59.0.3} [Immibis Core](immibis-core-59.0.3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    inventorytweaks{1.59-dev-152-cf6e263} [Inventory Tweaks](InventoryTweaks-1.59-dev-152.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    LiquidXP{59.0.0} [Liquid XP](liquid-xp-59.0.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    MineFactoryReloaded|CompatAppliedEnergistics{1.7.10R2.8.0RC3} [MFR Compat: Applied Energistics](MineFactoryReloaded-[1.7.10]2.8.0RC3-591.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    MineFactoryReloaded|CompatAtum{1.7.10R2.8.0RC2} [MFR Compat: Atum](MineFactoryReloaded-[1.7.10]2.8.0RC3-591.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    MineFactoryReloaded|CompatBackTools{1.7.10R2.8.0RC3} [MFR Compat: BackTools](MineFactoryReloaded-[1.7.10]2.8.0RC3-591.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    MineFactoryReloaded|CompatBuildCraft{1.7.10R2.8.0RC3} [MFR Compat: BuildCraft](MineFactoryReloaded-[1.7.10]2.8.0RC3-591.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    MineFactoryReloaded|CompatChococraft{1.7.10R2.8.0RC2} [MFR Compat: Chococraft](MineFactoryReloaded-[1.7.10]2.8.0RC3-591.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    MineFactoryReloaded|CompatExtraBiomes{1.7.10R2.8.0RC2} [MFR Compat: ExtraBiomes](MineFactoryReloaded-[1.7.10]2.8.0RC3-591.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    MineFactoryReloaded|CompatForestry{1.7.10R2.8.0RC3} [MFR Compat: Forestry](MineFactoryReloaded-[1.7.10]2.8.0RC3-591.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    MineFactoryReloaded|CompatForgeMicroblock{1.7.10R2.8.0RC3} [MFR Compat: ForgeMicroblock](MineFactoryReloaded-[1.7.10]2.8.0RC3-591.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    MineFactoryReloaded|CompatIC2{1.7.10R2.8.0RC3} [MFR Compat: IC2](MineFactoryReloaded-[1.7.10]2.8.0RC3-591.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    MineFactoryReloaded|CompatMystcraft{1.7.10R2.8.0RC2} [MFR Compat: Mystcraft](MineFactoryReloaded-[1.7.10]2.8.0RC3-591.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    MineFactoryReloaded|CompatPams{1.7.10R2.8.0RC2} [MFR Compat: Pam's Mods](MineFactoryReloaded-[1.7.10]2.8.0RC3-591.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    ProjRed|Core{4.5.1.51} [ProjectRed](ProjectRed-Base-1.7.10-4.5.1.51.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    ProjRed|Exploration{4.5.1.51} [ProjectRed-Exploration](ProjectRed-World-1.7.10-4.5.1.51.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    MineFactoryReloaded|CompatProjRed{1.7.10R2.8.0RC2} [MFR Compat ProjectRed](MineFactoryReloaded-[1.7.10]2.8.0RC3-591.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    MineFactoryReloaded|CompatRailcraft{1.7.10R2.8.0RC3} [MFR Compat: Railcraft](MineFactoryReloaded-[1.7.10]2.8.0RC3-591.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    MineFactoryReloaded|CompatRP2{1.7.10R2.8.0RC2} [MFR Compat: RP2](MineFactoryReloaded-[1.7.10]2.8.0RC3-591.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    MineFactoryReloaded|CompatSufficientBiomes{1.7.10R2.8.0RC2} [MFR Compat: Sufficient Biomes](MineFactoryReloaded-[1.7.10]2.8.0RC3-591.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    MineFactoryReloaded|CompatThaumcraft{1.7.10R2.8.0RC3} [MFR Compat: Thaumcraft](MineFactoryReloaded-[1.7.10]2.8.0RC3-591.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    ThermalExpansion{1.7.10R4.0.0B5} [Thermal Expansion](ThermalExpansion-[1.7.10]4.0.0B5-13.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    MineFactoryReloaded|CompatThermalExpansion{1.7.10R2.8.0RC3} [MFR Compat: Thermal Expansion](MineFactoryReloaded-[1.7.10]2.8.0RC3-591.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    TwilightForest{2.3.2} [The Twilight Forest](twilightforest-1.7.10-2.3.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    MineFactoryReloaded|CompatTwilightForest{1.7.10R2.8.0RC3} [MFR Compat: TwilightForest](MineFactoryReloaded-[1.7.10]2.8.0RC3-591.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    MineFactoryReloaded|CompatVanilla{1.7.10R2.8.0RC3} [MFR Compat: Vanilla](MineFactoryReloaded-[1.7.10]2.8.0RC3-591.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    AencEx{0.0.1} [AencEx](MoreEnchantments-1.7.X-1.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    me{1.1} [More Enchantments](MoreEnchantments-1.7.X-1.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    NEIPlugins{1.1.0.11-unofficial} [NEI Plugins Unofficial](NEIPlugins-MC1.7.10-1.1.0.11-unofficial.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    NetherOres{1.7.10R2.3.0RC3} [Nether Ores](NetherOres-[1.7.10]2.3.0RC3-84.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    ObsidiPlates{3.0.0.18} [ObsidiPlates](ObsidiPlates-1.7.10-universal-3.0.0.18.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    MapWriter{2.1.1} [MapWriter](Opis-1.2.3_1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    Opis{1.2.3} [Opis](Opis-1.2.3_1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    progressiveautomation{1.4.12} [Progressive Automation](ProgressiveAutomation-1.7.10-1.4.12.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    ProjRed|Transmission{4.5.1.51} [ProjectRed-Transmission](ProjectRed-Integration-1.7.10-4.5.1.51.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    ProjRed|Transportation{4.5.1.51} [ProjectRed-Transportation](ProjectRed-Mechanical_beta-1.7.10-4.5.1.51.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    ProjRed|Compatibility{4.5.1.51} [ProjectRed-Compatibility](ProjectRed-Compat-1.7.10-4.5.1.51.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    ProjRed|Integration{4.5.1.51} [ProjectRed-Integration](ProjectRed-Integration-1.7.10-4.5.1.51.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    ProjRed|Illumination{4.5.1.51} [ProjectRed-Illumination](ProjectRed-Lighting-1.7.10-4.5.1.51.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    ProjRed|Expansion{4.5.1.51} [ProjectRed-Expansion](ProjectRed-Mechanical_beta-1.7.10-4.5.1.51.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    RandomThings{2.1.9} [Random Things](RandomThings-2.1.9.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    RedstoneArsenal{1.7.10R1.1.0B4} [Redstone Arsenal](RedstoneArsenal-[1.7.10]1.1.0B4-10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    SpiceOfLife{1.2.2} [The Spice of Life](SpiceOfLife-mc1.7.10-1.2.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    ThaumcraftMobAspects{1.7.2-2A} [Thaumcraft Mob Aspects](ThaumcraftMobAspects-1.7.2-2A.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    Waila{1.5.5} [Waila](Waila-1.5.5_1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    thaumicenergistics{0.7.3b} [Thaumic Energistics](thaumicenergistics-0.7.3b.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    wawla{1.0.9} [What Are We Looking At](Wawla-1.0.9_1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    weaponmod{v1.14.3} [Balkon's WeaponMod](weaponmod-1.14.3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    WR-CBE|Core{1.4.1.7} [WR-CBE Core](WR-CBE-1.7.10-1.4.1.7-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    WR-CBE|Addons{1.4.1.7} [WR-CBE Addons](WR-CBE-1.7.10-1.4.1.7-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    WR-CBE|Logic{1.4.1.7} [WR-CBE Logic](WR-CBE-1.7.10-1.4.1.7-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    McMultipart{1.1.0.311} [Minecraft Multipart Plugin](ForgeMultipart-1.7.10-1.1.0.311-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    ForgeMicroblock{1.1.0.311} [Forge Microblocks](ForgeMultipart-1.7.10-1.1.0.311-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    AE2 Version: stable rv1-stable-1 for Forge 10.13.0.1187
    AE2 Integration: IC2:OFF, RotaryCraft:OFF, RC:OFF, BC:OFF, MJ6:ON, MJ5:ON, RF:ON, RFItem:ON, MFR:ON, DSU:ON, FZ:OFF, FMP:ON, RB:OFF, CLApi:OFF, Waila:ON, InvTweaks:ON, NEI:ON, CraftGuide:OFF, Mekanism:OFF, ImmibisMicroblocks:OFF, BetterStorage:OFF
    Launched Version: 1.7.10-Forge10.13.2.1230
    LWJGL: 2.9.1
    OpenGL: AMD Radeon HD 6530D GL version 4.2.11627 Compatibility Profile Context, ATI Technologies Inc.
    GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

```
Is Modded: Definitely; Client brand changed to 'fml,forge'
Type: Client (map_client.txt)
Resource Packs: []
Current Language: English (US)
Profiler Position: N/A (disabled)
Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
Anisotropic Filtering: Off (1)
```

**Comment by WingsOfLife** [comment]
Fixed in v1.1.04
