### ISSUE TITLE
Tile Entity crash.

### ISSUE THREAD

**Issue by Unrepentant-Atheist** [WingsOfLife/DynamicLiquidTanks_v2.0#4]
Placing tank blocks often, not always, results in a crash:

http://paste.ee/p/zPiyz
http://paste.ee/p/HnPrC

**Comment by WingsOfLife** [comment]
Can you provide more information about this? Where you are placing the tanks? Are there other tanks near by? Do they have a controller near?

**Comment by Unrepentant-Atheist** [comment]
There was no controller. I just wanted to place the tank to see if the shape was to my liking. First few worked, somewhere in the middle it crashed.

The second log was after I restarted and started to remove the placed tanks.

**Comment by WingsOfLife** [comment]
Resolved and fixed. Will be updated in v0.0.3
