### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by LTNightshade** [WingsOfLife/DynamicLiquidTanks_v2.0#5]
Created a tank without Controller and tried to fill lava into it with a fluiduct from TE3.
-> server crashed, and doesn't restart.

crash report : http://pastebin.com/Sa1f45dc

**Comment by WingsOfLife** [comment]
What version of DLT is this?

**Comment by LTNightshade** [comment]
i'm playing FTB Horizons 1.0.7 that contains DLT2 v0.0.2.

**Comment by WingsOfLife** [comment]
Thank you. Fixed in next version.
