### ISSUE TITLE
Capacity Upgrades cause render glitches

### ISSUE THREAD

**Issue by Zarathul** [WingsOfLife/DynamicLiquidTanks_v2.0#8]
Installing an Upgrade Modul and any number of Capacity Upgrades causes constant up and down shifting of the fluid level, visible both in the Tank Blocks and in the Tank Controller gui. It doesn't matter if the Upgrade Modul is placed before filling the tank with liquid or after.

**Comment by WingsOfLife** [comment]
How long does this occur for? It should only be temporary until the tanks all balance eachother out.

**Comment by Zarathul** [comment]
After about 5 minutes I stopped watching it. So if it ever stops it takes way to long in my opinion. Considering this was only a 2x2x2 tank.

**Comment by WingsOfLife** [comment]
Yes 5 minutes is far too long. Thank you I will look into it.
