### ISSUE TITLE
NPE on filling

### ISSUE THREAD

**Issue by tahg** [WingsOfLife/DynamicLiquidTanks_v2.0#9]
Got this error: http://pastebin.com/K1CkTX14
Tried to fill a tank without a controller from a Thermal Expansion tank.

**Comment by tahg** [comment]
Possibly a dupe of #5, but unsure of the version I have.  The filename says DLT2 0.0.3, but the Mod Info says 0.0.2

**Comment by WingsOfLife** [comment]
This has been fixed in a version not yet released. Thank you :)
